### ISSUE TITLE
Cluster Notable "Blood Artist" has no results

### ISSUE THREAD

**Issue by TWCCarlson** [NeverDecaf/PoE-Info#10]
[Cluster Jewel Notable Blood Artist](https://cdn.discordapp.com/attachments/145719962235830272/867211598213152768/unknown.png) cannot be looked up using ['-n blood artist' or '-ns blood artist'](https://i.imgur.com/zacxEIo.png).

**Comment by NeverDecaf** [comment]
The data source is the [wiki](https://pathofexile.fandom.com/wiki/List_of_cluster_jewel_notable_passive_skills), so if it isn't on there it won't show up on the bot.

**Comment by NeverDecaf** [comment]
The bot has been updated to use poewiki.net; the data should be more up to date as the new wiki gets filled out.
