### ISSUE TITLE
can't get currency data

### ISSUE THREAD

**Issue by sab9527** [NeverDecaf/PoE-Info#12]
no error , the other funtion success . how to fix it ? 
thank
https://i.imgur.com/ccKUjBT.png

**Comment by NeverDecaf** [comment]
Did you run `python db.py` first?

**Comment by sab9527** [comment]
yes, maybe i forget this.

> Manually prepared style variants included for these items:
> 
> (Make sure they are still correct)
> 
> Traceback (most recent call last):
>   File "f:\POEBOT\PoE-Info-master\db.py", line 209, in <module>
>     a.add_items_async(scrape_poe_wiki.scrape_passive_skills(),'passive_skills')
>   File "f:\POEBOT\PoE-Info-master\scrape_poe_wiki.py", line 430, in scrape_passive_skills
>     res['desc'] = remove_wiki_formats(html.unescape(res['desc']))
> KeyError: 'desc'

**Comment by NeverDecaf** [comment]
Thank you, that is very helpful.

**Comment by NeverDecaf** [comment]
Okay, try updating your `scrape_poe_wiki.py` to the latest version and then run `python db.py -f`.

**Comment by sab9527** [comment]
thank , the bot fix .
have the other error but i think it's fine.

https://i.imgur.com/q7gB3RW.png

**Comment by NeverDecaf** [comment]
You're welcome.
Those errors are normal, it's fine.
