### ISSUE TITLE
Running db.py and bot.py

### ISSUE THREAD

**Issue by TheFafurion** [NeverDecaf/PoE-Info#14]
**Hello, i want to ask, im trying to run my own copy of ur bot. But im strugle at how to run db.py  and i get this:**

root@localhost:/media/PoE-Info-master# python3 db.py
Traceback (most recent call last):
  File "db.py", line 2, in <module>
    import scrape_poe_wiki
  File "/media/PoE-Info-master/scrape_poe_wiki.py", line 14, in <module>
    import cloudscraper

**Also when im trying to run bot.py**

root@localhost:/media/PoE-Info-master# python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 6, in <module>
    import db
  File "/media/PoE-Info-master/db.py", line 2, in <module>
    import scrape_poe_wiki
  File "/media/PoE-Info-master/scrape_poe_wiki.py", line 14, in <module>
    import cloudscraper
ModuleNotFoundError: No module named 'cloudscraper'

**I dont know if command is correct or im missing something. Can u help me out? thanks**

**Comment by NeverDecaf** [comment]
You are missing required packages. `pip install -r requirements.txt`

**Comment by TheFafurion** [comment]
Hello, sorry for late respond, I have been at work for 16hours

**I wrote ur command and I get this:** 

root@localhost:/media/PoE-Info-master# pip install -r requirements.txt
Collecting aiohttp==3.7.4.post0 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement aiohttp==3.7.4.post0 (from -r requirements.txt (line 1)) (from versions: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.21.4, 0.21.5, 0.21.6, 0.22.0a0, 0.22.0b0, 0.22.0b1, 0.22.0b2, 0.22.0b3, 0.22.0b4, 0.22.0b5, 0.22.0b6, 0.22.0, 0.22.1, 0.22.2, 0.22.3, 0.22.4, 0.22.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6.post1, 2.0.7, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0a4, 2.3.0, 2.3.1, 2.3.2b2)
No matching distribution found for aiohttp==3.7.4.post0 (from -r requirements.txt (line 1))

**Comment by NeverDecaf** [comment]
Looks like the pip version of py-cord (still) hasn't been updated; you can install the latest directly from source with `pip install -U git+https://github.com/Pycord-Development/pycord` I believe you'll need git installed (and in your PATH) in order to run this command.

**Comment by TheFafurion** [comment]
root@localhost:/media/PoE-Info-master# pip install -r requirements.txt
Requirement already satisfied: aiohttp==3.7.4.post0 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (3.7.4.post0)
Requirement already satisfied: async-timeout==3.0.1 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied: attrs==21.4.0 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (21.4.0)
Collecting certifi==2021.10.8
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Requirement already satisfied: chardet==4.0.0 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (4.0.0)
Collecting charset-normalizer==2.0.9
  Using cached charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Collecting cloudscraper==1.2.58
  Using cached cloudscraper-1.2.58-py2.py3-none-any.whl (96 kB)
Collecting dateparser==1.1.0
  Using cached dateparser-1.1.0-py2.py3-none-any.whl (288 kB)
Requirement already satisfied: idna==3.3 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (3.3)
Collecting lxml==4.7.1
  Using cached lxml-4.7.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.9 MB)
Collecting multidict==5.2.0
  Using cached multidict-5.2.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (174 kB)
**ERROR: Could not find a version that satisfies the requirement py-cord==2.0.0a4738+g99e2312f (from versions: 1.7.3)
ERROR: No matching distribution found for py-cord==2.0.0a4738+g99e2312f**

Still getting this

**Comment by NeverDecaf** [comment]
If you installed py-cord correctly with the command above you can just delete the py-cord line in requirements.txt and try again.

**Comment by TheFafurion** [comment]
I removed the line and I think its working now, thanks of ur time a lot :)

**Comment by NeverDecaf** [comment]
You're welcome.

Yes, you can use cron on Linux or task scheduler on Windows.
