### ISSUE TITLE
Cannot Run db.py

### ISSUE THREAD

**Issue by Rebrandsoft** [NeverDecaf/PoE-Info#3]
Hello, firstly thanks for a good job and the great Poe bot. I'm trying to self-host the bot but when I try to run the db.py I'm getting this error:

```
Traceback (most recent call last):
  File "C:/Users/rebra/PycharmProjects/POE-Discord-Bot/db.py", line 231, in <module>
    data = scrape_poe_wiki.get_ninja_prices(league)
  File "C:\Users\rebra\PycharmProjects\POE-Discord-Bot\scrape_poe_wiki.py", line 486, in get_ninja_prices
    elif int(x['gemLevel']) == 1 and int(x['gemQuality']) == 20:
KeyError: 'gemQuality'
```

Process finished with exit code 1

https://imgur.com/GYhWHR4

Also, can you create Python requirements.txt so this will speed up the process.

**Comment by NeverDecaf** [comment]
Looks like poe.ninja omits gem quality in some cases, I've updated the code and it should work now.
I also added `requirements.txt`, it was in my `.gitignore` for some reason.
