### ISSUE TITLE
Failure to launch on the bot.py

### ISSUE THREAD

**Issue by SystemAnonymous** [NeverDecaf/PoE-Info#9]
Hey there. 

So I am trying to host my own instance for the bot. I ran the db.py which it created a new folder/files.
But when I run the bot.py it closes the cmd quickly.

I get this error.
Traceback (most recent call last):
File "POE-Info\bot.py", line 6, in < module >
import db
File "POE-Info\db.py", line 2, in < module >
import scrape_poe_wiki
File "POE-Info\scrape_poe_wiki.py", line 8, in < module >
import requests, re, datetime, time, json, os
ModuleNotFoundError: No module named 'requests'

Any help will be greatly appreciated. Thank you =)

**Comment by NeverDecaf** [comment]
run `pip install -r requirements.txt`

**Comment by SystemAnonymous** [comment]
Thank you very much =)
